### ISSUE TITLE
Missing assembly-final.msimpl.fa in multik mode

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [ekimb/rust-mdbg#10]
Hello,

Thank you for this tool.

I ran mdbg with the following command line:
`multik reads.fastq.gz assembly 56 10 1000`

I get the files assembly-k*.gfa, assembly-k*.msimpl.gfa and assembly-k*.msimpl.fa with k from 10 to 1000, but I do not get the final output assembly-final.msimpl.fa.

**Comment by rchikhi** [comment]
hi Nadège, ah yes, small bug in multi-k script, fixed now; thanks for letting me know.

**Comment by nadegeguiglielmoni** [comment]
Hello,

I launched the tool again, and now the final files are created but they are (almost) empty: 

```
::::::::::::::
assembly-final.gfa
::::::::::::::
H	VN:Z:1
::::::::::::::
assembly-final.msimpl.fa
::::::::::::::
::::::::::::::
assembly-final.msimpl.gfa
::::::::::::::
H	VN:Z:1
```

**Comment by rchikhi** [comment]
hm that's odd, I just did a clean install and ran `bash ../utils/multik  reads-0.00.fa.gz test 1` in the example folder and got a correct result. Can you please print your console output?

**Comment by rchikhi** [comment]
also I fixed a bug that occurs on some systems, please update the repository again..

**Comment by ekimb** [comment]
Closing this issue, feel free to ping if you want to reopen it!
