### ISSUE TITLE
magic_simplify crashes while running in Docker container on HPC cluster

### ISSUE THREAD

**Issue by fischer-hub** [ekimb/rust-mdbg#11]
Hey! I'm currently trying to run rust-mdbg as part of a fungi genome assembly pipeline using nextflow and docker containers on an HPC cluster and I'm running into these issues where the magic_simplify script crashes with os error 30 : read-only file system.
I already checked the docker container and made sure the rust-mdbg dir is not read-only so I'm not sure what exactly is happening here. Maybe someone knows whats up?
I'm using singularity to run the docker containers on the HPC cluster I just hope this is not some compatibility issue with singularity/rust..

[command.log](https://github.com/ekimb/rust-mdbg/files/6775865/command.log)

**Comment by rchikhi** [comment]
Hi, it seems the `/usr/bin/time` tool isn't present on your system. How comes? Maybe try to install it with `sudo apt install time`

**Comment by fischer-hub** [comment]
Thanks for the answer! 
You are right, somehow the `time` tool got overwritten in the container building process. I fixed that but sadly the os error persists.
I think this issue is singularity related tho because using just docker everything ran fine. Sadly I can't do much about the singularity setup on the HPC cluster I'm working on.
Anyway I'll close this issue since its singularity related and not rust-mdbg related.

**Comment by rchikhi** [comment]
Indeed seems you should find a way to mount the filesystem as writeable.
