### ISSUE TITLE
example.sequences file

### ISSUE THREAD

**Issue by samlipworth** [ekimb/rust-mdbg#12]
Sorry if I'm being slow but when I create the gfa file multiple .sequences files are created but when then in the readme to_basespace takes only a single example.sequences file. Where does this come from? Do you combine the .sequences files in some way or..?

Thanks!

**Comment by rchikhi** [comment]
Ah it's a bit ambiguous but to_basespace takes the prefix as input, so if you have multiple .sequences files, just input the name of the prefix of those files

**Comment by samlipworth** [comment]
Aha fixed thanks. Do you mind if I ask one more thing? In the paper you have a lovely figure where you assemble Grace/Zam's massive genome collection and then show dominant species for the largest collected components - how did you assign species representation from the graph? (sorry if this is obvious in the paper but I can't see it).  Thanks.

**Comment by rchikhi** [comment]
It's not obvious. (and thanks for the kind words). I used this script to retrieve `taxid`'s from ENA: https://github.com/ekimb/rust-mdbg/blob/master/experiments/661k_genomes/retrieve_wcc_genomes.sh (as part of this pipeline: https://github.com/ekimb/rust-mdbg/blob/master/experiments/661k_genomes/graph_commands)

**Comment by ekimb** [comment]
Closing this issue, but feel free to reopen if you would like!
