### ISSUE TITLE
Differences between uncompressed & compressed fastq files

### ISSUE THREAD

**Issue by gconcepcion** [ekimb/rust-mdbg#14]
This seems like a bug, but maybe I'm just misunderstanding something with how mdbg works.

I discovered this after trying to run several human assemblies of varying input coverage (20x,30x,40x,50x) starting from hifi_reads.fq.gz files.

The contiguity (n50) of all of the assemblies was in the same ballpark as the read n50 and there appeared to be no benefit to increased coverage. This coupled with the poor results in general had me scratching my head so I tried a different test dataset that was an uncompressed hifi_reads.fq and I got a great assembly.

Curiosity piqued, I went back an unzipped the 20x coverage point I had tried earlier and got a much better assembly. 

See attached logs for logs from both the 20x assemblies starting from both hifi_reads.fq and hifi_reads.fq.gz

Is this an actual bug, or is it just user error?

[hifi_reads_gzipped.log](https://github.com/ekimb/rust-mdbg/files/7187413/hifi_reads_gzipped.log)
[hifi_reads.log](https://github.com/ekimb/rust-mdbg/files/7187415/hifi_reads.log)

**Comment by ekimb** [comment]
Seems like there is an issue with the FASTQ parser with `fq.gz` files... There are fewer reads obtained when the gzipped FASTQ is decompressed. 

Have you formatted your FASTQ using `seqtk` as shown [here](https://github.com/ekimb/rust-mdbg#input)? Can you provide the file so I can also run it on my end? I'm suspecting that this is somehow related to multi-line sequences in the file.

**Comment by gconcepcion** [comment]
I didn't run the seqtk line but i'm running it now on the same dataset to test. I suspect it will work since it will be an unzipped fasta file at the end.

I uploaded The HG002 20x dataset that I'm using here and it should be available for the next 30 days:
ftp://mdbg:hg002@ftp2.pacificbiosciences.com/data/HG002_20x.fq.gz

I should mention that this dataset is comprised of 2 x *.ccs.fastq files that I `cat` 'd together:
`$ cat m54119U_210315_232339.ccs.fastq m54119U_210313_073345.ccs.fastq >HG002_20x.fq

on a slightly related note - Are there plans to be able to use a list of fastq files for input, rather than a single concatenated file?

**Comment by rchikhi** [comment]
Hi, we didn't spend that much time on improving the fastq/fastq.gz parsing part of mdbg, the state of parallel fastq parsing in Rust isn't great last time I checked.  For now the `seqtk` preparation route is highly recommended (and thus we also don't have immediate plans for a list of files as input). Was your original file multi-line? This issue is getting a year old and I'll mark is closed unless there is new developments on your side. Thanks for testing mdbg though!
