### ISSUE TITLE
about header in *.msimpl.fa

### ISSUE THREAD

**Issue by majunyeong1064** [ekimb/rust-mdbg#15]
After running rust-mdbg and magic_simplify script, *.msimpl.fa is created.
In my .msimpl.fa file, there are >utg0000001l and >utg0000034c, the whats the mean of the l and c? thanks

**Comment by rchikhi** [comment]
It's added by `gfatools` and I believe it's related to whether the contig is linear or circular (https://github.com/lh3/gfatools/blob/195273ef67536c36fd24242e9bb0f17053f8ab8b/gfa-asm.c#L667)
