### ISSUE TITLE
Assembly result problem

### ISSUE THREAD

**Issue by lxingze** [ekimb/rust-mdbg#18]
Hello,
I have encountered some problems when testing the data here, please answer them. Thank you!
I use D. melanogaster HiFi reads for assembly using the following parameters:

`rust-mdbg SRR10238607_subreads.fastq.gz --threads 150 --prefix Dme`
Assembly result: 369.64Mb; contig N50 265602bp

`rust-mdbg SRR10238607_subreads.fastq.gz --threads 150 --prefix Dme -k 35 -l 12 -d 0.002`
Assembly result: 401.55Mb; contig N50 69278bp

The above two results are quite different from the estimated genome size and the contig N50 value is low. Do you know what causes the above?

**Comment by rchikhi** [comment]
dear @lxingze , it seems you are assembling the HiFi subreads and not the consensus reads. Please use the consensus reads provided here:
https://obj.umiacs.umd.edu/marbl_publications/hicanu/index.html
-> https://obj.umiacs.umd.edu/marbl_publications/hicanu/dmel_hifi_40x.fasta.gz
