### ISSUE TITLE
Problems with to_basespace: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/to_basespace.rs:216:55

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [ekimb/rust-mdbg#19]
Hello,

I have received an error message as following when ran "to_basespace --gfa example.unitigs.gfa --sequences example.sequences" with example data.

Could you give me some advice? Thanks!

Zhiliang

[zhiliang@localhost example]$ RUST_BACKTRACE=full ../target/release/to_basespace --gfa example.unitigs.gfa --sequences example.sequences
Done parsing GFA, got 1 unitigs.
Done parsing .sequences file, recorded 0 sequences.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/to_basespace.rs:216:55
stack backtrace:
   0:     0x55f28d16a8f0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f28d16a8f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f28d16a8f0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f28d16a8f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f28d18ab7c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f28d168315 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55f28d16c85b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f28d16c85b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f28d16c85b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55f28d16c331 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55f28d16cf24 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55f28d16c9d7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55f28d16adec - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f28d16c969 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55f28d0f2e51 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55f28d0f2d9d - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55f28d0fb5a6 - to_basespace::main::hf31f3484661a5776
  17:     0x55f28d0f6193 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf04ca134ae30e5e6
  18:     0x55f28d0f61a9 - std::rt::lang_start::{{closure}}::h9452ba2bf9a0a5ac
  19:     0x55f28d16d429 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  20:     0x55f28d16d429 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  21:     0x55f28d16d429 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  22:     0x55f28d16d429 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  23:     0x55f28d16d429 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  24:     0x55f28d0fc412 - main
  25:     0x7f6b9f66a555 - __libc_start_main
  26:     0x55f28d0f3621 - <unknown>
  27:                0x0 - <unknown>

**Comment by ekimb** [comment]
Hello @Zhiliang-Zhang,

The `--sequences` argument is actually a prefix, not the filename.

Can you try again with `--sequences example` and let me know?

Thanks!
Barış

**Comment by Zhiliang-Zhang** [comment]
Hi Barış,

I run successfully. Thanks for your quick response. I will close this comment.

Bests,
zhiliang
