### ISSUE TITLE
Unable to assemble the D.melanogaster genome from 24kb HiFi reads

### ISSUE THREAD

**Issue by sebschmi** [ekimb/rust-mdbg#21]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: BufferLimit }', src/main.rs:187:33

Reads taken from: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos2/sra-pub-run-17/SRR1023860/SRR10238607.1

Command: utils/multik `<reads>` `<output prefix>` 56

Happens both with and without homopolymer compression.

**Comment by rchikhi** [comment]
hmm weird, it worked for me, I did:

```
wget https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos2/sra-pub-run-17/SRR1023860/SRR10238607.1
fastq-dump SRR10238607.1
path/to/rust-mdbg/utils/multik SRR10238607.1.fastq prefix 6
```

finished with a N50 of 1.5 Mbp, 262 Mbp assembly size

**Comment by rchikhi** [comment]
can you please paste the first 5 lines of your fastq file? seems the crash is due to a problem parsing the beginning of the input

**Comment by sebschmi** [comment]
I am using a fasta file as in the quick start example. Here are its first few lines:

```
>file.1 1 length=25473
TATAAATAGAAAATGAAAATAATAAAACAGCTACGGAAACTGAATCGGCAAACTGAAATGGAAACTGAAA
AGTTGCTGCCCAAGTTGAGCGGCATAAATTTGCGGCGTGTTTAGTGTTTAGTCAGCTAACTTTTTGCAGC
CACTGTCCCAGGGACATTTGCGAAAGTTGGCCAACTGAAACAAATGGCAACAAATTGTAAATAAATAAAA
GTTTTTCGGCCACTCCGGGGCTGCATACATAAATCCCATTGAATAATGCCGATCAATTTCGGACTTTTGT
GCCATGCCGTGCCGGACAAAGTTTTTGCAGCAGTGTACACATACAGTGGCGGCCGCGTGAATAGCGCTGG
AAATTTTAACTTGCCATTCGCTGTAATTAAAATGTATTAGAATAATTGAAAATGAAAATGTATTGGGTTA
TATTTTATAGCCATTTAAAATATGATAATAAGTTTATATTTCATTGTTCATATTATTGTATTATTACTTT
CATTTCTACCGCACTTGCACACTGTCCCACATAATTTACAATTAGATTGTGTCTGCCGGAGACTTGGAAA
CTCGATGCTGAACTTGATTATGCTACCGAAACGGTTTTGTTAATGTTTATGGAAATTGTTTTTCCTCCAG
```

**Comment by rchikhi** [comment]
I think I see the problem, `rust-mdbg` dislikes multi-line FASTAs for now, please convert your reads: `seqtk seq -AU reads.unformatted.fa > reads.singleline.fa`

**Comment by sebschmi** [comment]
Thank you very much, it seems to work now after converting to single-line FASTA!
