### ISSUE TITLE
m1 arm support

### ISSUE THREAD

**Issue by jianshu93** [ekimb/rust-mdbg#22]
Hello rust-mdbg team,

It seems that there is no support for ARM structure yet, I have the following error when compiling on ARM64:

The following warnings were emitted during compilation:

warning: cc: error: unrecognized command-line option '-msse4.2'
warning: cc: error: unrecognized command-line option '-maes'
warning: cc: error: unrecognized command-line option '-mavx'
warning: cc: error: unrecognized command-line option '-mavx2'

error: failed to run custom build command for `fasthash-sys v0.3.2`

Caused by:
  process didn't exit successfully: `/Users/jianshuzhao/Github/rust-mdbg/target/release/build/fasthash-sys-17495dcf061597dc/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  TARGET = Some("aarch64-apple-darwin")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = None
  CC_aarch64_apple_darwin = None
  HOST_CC = None
  CC = None
  HOST = Some("aarch64-apple-darwin")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  DEBUG = Some("false")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wno-implicit-fallthrough" "-Wno-unknown-attributes" "-msse4.2" "-maes" "-mavx" "-mavx2" "-DT1HA0_RUNTIME_SELECT=1" "-DT1HA0_AESNI_AVAILABLE=1" "-Wall" "-Wextra" "-o" "/Users/jianshuzhao/Github/rust-mdbg/target/release/build/fasthash-sys-d509c7de4ba60bc4/out/src/fasthash.o" "-c" "src/fasthash.cpp"
  cargo:warning=cc: error: unrecognized command-line option '-msse4.2'
  cargo:warning=cc: error: unrecognized command-line option '-maes'
  cargo:warning=cc: error: unrecognized command-line option '-mavx'
  cargo:warning=cc: error: unrecognized command-line option '-mavx2'
  exit status: 1

  --- stderr
  thread 'main' panicked at '

  Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wno-implicit-fallthrough" "-Wno-unknown-attributes" "-msse4.2" "-maes" "-mavx" "-mavx2" "-DT1HA0_RUNTIME_SELECT=1" "-DT1HA0_AESNI_AVAILABLE=1" "-Wall" "-Wextra" "-o" "/Users/jianshuzhao/Github/rust-mdbg/target/release/build/fasthash-sys-d509c7de4ba60bc4/out/src/fasthash.o" "-c" "src/fasthash.cpp" with args "cc" did not execute successfully (status code exit status: 1).

  ', /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  fatal runtime error: failed to initiate panic, error 5
warning: build failed, waiting for other jobs to finish...
error: build failed

Any possibilities to provide support?

Thanks,

Jianshu

**Comment by rchikhi** [comment]
Hi, no support planned here sorry, I don't use that hardware. Any pull request is of course welcome.

**Comment by jianshu93** [comment]
It seems to me that rust-fasthash (rust binding to smhash) is the only one that is platform specific, I am wondering what hash was used in the smhash because there so many other rust implemented hash repo including murmurhash3 et.al.

Jianshu

**Comment by rchikhi** [comment]
thanks for the analysis Jianshu! Turns out fasthash was even commented out from the code, so I removed it from the dependencies. Can you compile now?

**Comment by asl** [comment]
I can confirm it builds now on M1

**Comment by jianshu93** [comment]
Hello All,

I can also confirm that it builds on M1 Pro/Max and it works for the testing input.

Many thanks for the work.

Jianshu

**Comment by rchikhi** [comment]
great!
