### ISSUE TITLE
Missing dependencies in docker image

### ISSUE THREAD

**Issue by MrTomRod** [ekimb/rust-mdbg#31]
Hi!

Thanks for your incredibly fast assembler!

I noticed that the following dependencies are missing in the docker image https://hub.docker.com/r/wckdouglas/mdbg

- time
- bc
- seqtk
- gfatools

I installed them using these commands:

```bash
apt install time bc seqtk less
git clone https://github.com/lh3/gfatools && \
  cd gfatools/ && \
  make && \
  ln ./gfatools /bin/ && \
  cd ..
```

Best, Thomas

**Comment by rchikhi** [comment]
thank you for reporting this Thomas. It appears this Docker image has been created by someone else, I'm unsure if we can act on it
