### ISSUE TITLE
seq_io dependence

### ISSUE THREAD

**Issue by lzqzz** [ekimb/rust-mdbg#32]
Hello, I encountered an "unresolved import `seq_io::BaseRecord`" error while executing cargo build --release. The cargo. toml file was imported using git. Why does this problem arise？Is this problem like a problem with the seq_io package or did the import of dependencies fail？

**Comment by dirkjanvw** [comment]
Not the author or collaborator on this repo, but I did find a solution to the build error to be made in `Cargo.toml`:
```diff
-seq_io= { git = "https://github.com/markschl/seq_io" }
+seq_io= { git = "https://github.com/markschl/seq_io" , rev = "8ffc720fd73f2ab1e4771802a25c25e5fdd8fbdf" }
```

**Comment by lzqzz** [comment]
> Not the author or collaborator on this repo, but I did find a solution to the build error to be made in `Cargo.toml`:
> 
> ```diff
> -seq_io= { git = "https://github.com/markschl/seq_io" }
> +seq_io= { git = "https://github.com/markschl/seq_io" , rev = "8ffc720fd73f2ab1e4771802a25c25e5fdd8fbdf" }
> ```

Thank you for your reply! I have already resolved this issue.
