### ISSUE TITLE
Handle fasta with sequence over multiple lines gracefully

### ISSUE THREAD

**Issue by rmcolq** [ekimb/rust-mdbg#5]
If I input a fasta where the sequence is split over multiple lines, I get the following:
```
Parsing input sequences...
thread '<unnamed>' panicked at 'Non-ACGTN nucleotide encountered!', /Users/rmcolq/.cargo/registry/src/github.com-1ecc6299db9ec823/nthash-0.5.0/src/lib.rs:43:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Thread pool worker panicked', /Users/rmcolq/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:236:13
```
And then it hangs without quitting. Removing the new lines fixes it. 

I came across this when I tried testing out with some reference sequences to see what would happen which I know isn't the normal use case.

**Comment by rchikhi** [comment]
Hehe yes, it's documented in the readme (https://github.com/ekimb/rust-mdbg#input), I just wanted to do faster parsing and avoid a copy to delete the last character. 
One way to get around that is to use the `--reference` command line parameter. It will accept multiline FASTAs but won't do any filtering (equivalent to `--minabund 1`). 
But the FASTA/FASTQ parsing here is due for an overhaul anyway (https://twitter.com/IvanSovic/status/1403362961868136449) so hopefully in the future it will handle multiline FASTAs seamlessly.

**Comment by rmcolq** [comment]
Oops, thank you!
