### ISSUE TITLE
Example produces empty files

### ISSUE THREAD

**Issue by rmcolq** [ekimb/rust-mdbg#6]
I have both rust and gfatools installed and ran the following:
```
cargo build --release
cd example
../target/release/rust-mdbg reads-0.00.fa.gz -k 7 --density 0.0008 -l 10 --minabund 2 --prefix example
../utils/magic_simplify example
```
This created files:
```
example.13123829760.sequences	example.13128048640.sequences	example.13132267520.sequences	example.13136486400.sequences	example.gfa			example.msimpl.gfa
example.13125939200.sequences	example.13130158080.sequences	example.13134376960.sequences	example.13138595840.sequences	example.msimpl.fa
```
and `example.gfa` contains lots of node and edge lines, but `example.msimpl*` are both empty. I tried to track this down and found that:
1. The stat command in `utils/magic_simplify` only works on linux, the equivalent on macOS would be `stat -f %z`
2. The problem seems to be when running `gfatools asm example.tmp2.gfa  -t 10,50000 -b 100000 -t 10,100000  -b 1000000 -t 10,150000 -b 1000000 -u > example.tmp3.gfa` which results in an empty file, even though the input file contains 1 sequence unitig

What is the expected output for this example?

**Comment by rchikhi** [comment]
Hi Rachel,
oh thanks for pointing this out! & for the suggested `stat` fix. A recent change in `magic_simplify` broke the example.  I'm pushing a quickfix now, hopefully should fix the example.

**Comment by ekimb** [comment]
Note that `utils/magic_simplify` includes a collection of aggressive graph simplifications that are meant to tackle errors in assemblies. Since the example is a synthetic error-free read set, you can use `gfatools asm -u` and `gfa2fasta.sh` instead (see [here](https://github.com/ekimb/rust-mdbg#running-an-example)).

Hope that helps!
