### ISSUE TITLE
Multi-k input file

### ISSUE THREAD

**Issue by RNieuwenhuis** [ekimb/rust-mdbg#9]
Hi,

I used the multi-k script with just 
`./multik reads.fastq.gz prefix 12`

The first line of the log file reads:
`avg readlen: 4198262, max k: 11965`

This seemed completely off. 

From the `multik` script I read that you sample 5000 reads from a **fasta file** and determine the average from that. 

In the README the example command contains a **gzipped fastq file**. Could you please fix the example and maybe highlight that `multik` expects a fasta file instead of fastq files.

**Comment by rchikhi** [comment]
hi, indeed thanks for letting us know of this bug, the `multik` script should now support fasta/fastq/gzipped files.
